language: go
go:
 - 1.6.3

script:
 - go test -v ./...

release:
  mkdir -p release
  GOOS=linux GOARCH=amd64 go build -o release/go-blog-linux-amd64-$(package)
  GOOS=linux GOARCH=386 go build -o release/go-blog-linux-386-$(package)
  GOOS=linux GOARCH=arm go build -o release/go-blog-linux-arm-$(package)

before_deploy:
  - sudo zip -j -r "./release/go-blog-$TRAVIS_BRANCH-v$RELEASE_VERSION+$TRAVIS_BUILD_NUMBER.zip" ./release/go-blog-linux-amd64-$(package)

deploy:
  provider: elasticbeanstalk
  edge: true
  bucket_name: '$ELB_BUCKET'
  app: '$ELB_APP'
  env: '$ELB_ENV'
  region: '$ELB_REGION'
  zip_file: './release/go-blog-$TRAVIS_BRANCH-v$RELEASE_VERSION+$TRAVIS_BUILD_NUMBER.zip'
  access_key_id:
    secure: '$ELB_ACCESS_KEY_ID'
  secret_access_key:
    secure: '$ELB_SECRET_ACCESS_KEY'