language: go
go:
 - 1.6.3

script:
 - go test -v ./...

release:
  mkdir -p release
  GOOS=linux GOARCH=amd64 go build -o ./release/go-blog-linux-amd64
  GOOS=linux GOARCH=386 go build -o ./release/go-blog-linux-386
  GOOS=linux GOARCH=arm go build -o ./release/go-blog-linux-arm

before_deploy:
  - cp ./release/go-blog-linux-amd64 ./release/application | zip -j -r "./release/go-blog-elb.zip" ./release/application

deploy:
  provider: elasticbeanstalk
  edge: true
  bucket_name: '$ELB_BUCKET'
  app: '$ELB_APP'
  env: '$ELB_ENV'
  region: '$ELB_REGION'
  zip_file: './release/go-blog-elb.zip'
  access_key_id:
    secure: '$ELB_ACCESS_KEY_ID'
  secret_access_key:
    secure: '$ELB_SECRET_ACCESS_KEY'